### ISSUE TITLE
[oAuth2] redirect_uri (table expected, got string)

### ISSUE THREAD

**Issue by carbeman** [Mashape/kong#1423]
### Summary

In reference to: https://groups.google.com/forum/#!topic/konglayer/z9i0YHOyNVg

The plugins seems to store redirect_uri as string but after search a table. This behaviour generate a **An unexpected error occurred** response when invoke /oauth2/authorize resource.

### Steps To Reproduce

1. Follow this steps https://github.com/Mashape/kong-oauth2-hello-world
2. Do a request to /oauth2/authorize resource for obtains code

### Additional Details & Logs

- Kong version 
0.8.3

- Kong configuration 
Standard, with oauth2 plugin

- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
2016/07/16 08:53:21 [error] 898#0: *26264 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/tools/utils.lua:182: bad argument #1 to 'pairs' (table expected, got string)
stack traceback:
coroutine 0:
        [C]: in function 'pairs'
        /usr/local/share/lua/5.1/kong/tools/utils.lua:182: in function 'table_contains'
        /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:154: in function 'authorize'
        /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:406: in function 'execute'
        /usr/local/share/lua/5.1/kong/plugins/oauth2/handler.lua:12: in function 'access'
        /usr/local/share/lua/5.1/kong.lua:188: in function 'access'
        access_by_lua(nginx.conf:98):2: in function <access_by_lua(nginx.conf:98):1>, client: 192.168.69.1, server: _, request: "POST /oauth2/authorize HTTP/1.1", host: "test.com"

- Operating System
Debian 8.4

**Comment by thefosk** [comment]
This has been fixed with #1405 and will be available in the next version.

**Comment by carbeman** [comment]
Sorry @thefosk , i have applied your patch into access.lua file but my problem persists. I think the problem is still present in function _get_redirect_uri_.

The DB store redirect_uri as:

` ["http:\/\/192.168.69.1:9001"]`

and returing it as string, not as table.
if i try to replace, just for test before it return, client.redirect_uri with:

`client.redirect_uri = {"http:\\/\\/192.168.69.1:9001"}` 
`return client and client.redirect_uri or nil, client`

kong return me the code correctly.

Is correct this analysis?

**Comment by thefosk** [comment]
I think this is also related to this other fix: #1316.

**Comment by craigbeat** [comment]
Sorry to be a pain to ask, when (and how often) do you do release builds, specifically for Ubuntu? Just wondering when to expect the fix to appear.

Thanks.

**Comment by thefosk** [comment]
@craigbeat you can start playing with the Release Candidate at https://github.com/Mashape/kong/releases

It won't differ too much than the final version.
