### ISSUE TITLE
OAuth2 Plugin: Support for Angular2 hashtag URLs in redirect_uri

### ISSUE THREAD

**Issue by tbrownMT** [Mashape/kong#1459]
### Summary

It appears that while registering an application with the OAuth2 plugin, trying to set the  redirect_uri with an Angular route casues the error "fragment not allowed in 'http:\/\/localhost:8080\/#\/mypage\/'"

### Steps To Reproduce

1. Assuming you have an API and consumer configured with the OAuth2 plugin, issue the following curl:

curl http://mykong:8001/consumers/myconsumer/oauth2 \
    -d "name=Test App" \
    -d "redirect_uri=http://localhost:8080/#/mypage"

3.  Kong will respond with the following error:

{
  "redirect_uri": "fragment not allowed in 'http:\/\/localhost:8080\/#\/mypage\/'"
}

4. Try the same command, without the angular route marker (#):

curl http://mykong:8001/consumers/myconsumer/oauth2 \
    -d "name=Test App" \
    -d "redirect_uri=http://localhost:8080/mypage"

Note that it works.

### Additional Details & Logs

- Kong version: 0.8.3
- Kong configuration: default configuration (out of the box)
- CentOS 6

**Comment by thefosk** [comment]
This should be fixed in 0.9.0 (you can experiment with the RC1 already)

**Comment by joelmora** [comment]
In `0.11.0` I still have the issue, any thoughts?

![screen shot 2017-09-21 at 5 11 34 pm](https://user-images.githubusercontent.com/11574884/30721093-f3968532-9eef-11e7-9710-d4ddfaf3bb0f.png)

![screen shot 2017-09-21 at 5 12 15 pm](https://user-images.githubusercontent.com/11574884/30721113-0a3b1be0-9ef0-11e7-986b-74ea30dabb3a.png)
