### ISSUE TITLE
502 when proxying local service

### ISSUE THREAD

**Issue by montanaflynn** [Mashape/kong#163]
I'm trying to have Kong proxy running in docker to a service running on port `4444`.  Getting a 502 error from openresty. 

First I created the API in kong with this command:

```shell
 curl -i -X POST \
 --url http://127.0.0.1:8001/apis/ \
 --data 'name=kongdb' \
 --data 'target_url=http://127.0.0.1:4444' \
 --data 'public_dns=kongdb.org'
```

Then tested it and got this response:

```
$ curl 127.0.0.1:8000 -H "host: kongdb.org"
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>openresty/1.7.10.1</center>
</body>
</html>
```

Verified the service was running:

```
curl -I http://127.0.0.1:4444
HTTP/1.1 200 OK
Content-Type: text/html
Date: Sun, 26 Apr 2015 00:49:36 GMT
Connection: keep-alive
```

**Comment by rosscdh** [comment]
+1 had the same issue with localhost and adding 127.0.0.1    service_name.local to /etc/hosts does not seem to like hosts resolution. (osx)

**Comment by thefosk** [comment]
This issue has been fixed and will be available in the next release of Kong.

**Comment by mogui** [comment]
Which release? cause for me it's still not working this way, did we have to configure something in the docker image to let it proxy correctly?

**Comment by thefosk** [comment]
This should have been fixed a long time ago. Does the issue happen with the current latest version 0.5.2?

**Comment by thefosk** [comment]
@mogui if you are using `localhost`, it will local to the Docker container, so Kong expects the Docker container to also have an API running (which is not the case by default).

 Is your API running inside the Kong docker container, or is it running in another container?

**Comment by mogui** [comment]
yes it is running outside the container, the problem is within the docker container, I have to link it outside, anyway I've solved in another way !
Thanks anyway
