### ISSUE TITLE
Sporadic failure of DNS resolution

### ISSUE THREAD

**Issue by frederik79** [Mashape/kong#2524]
### Summary
We are running kong 0.10.2 inside docker within a OpenShift (Kubernetes) cluster.  

We get  DNS resolve error messages  [toip() name lookup failed] sporadically. In general, the error occurs in particular after a redeploy and eases after multiple calls.
Our /etc/resolv.conf features three entries. We tested commenting the individual nameserver entries in /etc/resolv.conf. However, the error occurs with any of the configured nameservers.

### Steps To Reproduce
sh-4.2# curl -vvv http://127.0.0.1:8001/apis
* About to connect() to 127.0.0.1 port 8001 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8001 (#0)
> GET /apis HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:8001
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Date: Mon, 15 May 2017 02:19:33 GMT
< Content-Type: application/json; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Access-Control-Allow-Origin: *
< Server: kong/0.10.2

{“message”:“An unexpected error occurred”}
* Connection #0 to host 127.0.0.1 left intact

### Additional Details & Logs
/usr/local/kong/error.log

[2:19] 
2017/05/15 02:19:33 [error] 120#0: *12369 [lua] responses.lua:107: handler(): [toip() name lookup failed]: dns server error; 3 name error, client: 127.0.0.1, server: kong_admin, request: “GET /apis HTTP/1.1”, host: “127.0.0.1:8001"

- Kong version: 0.10.2
- Operating System: docker image

**Comment by frederik79** [comment]
We get the a similar error if we access a configured api route. However, then the ph_host cannot be resolved. 

jingbai [11:28 AM] 
017/05/14 22:47:36 [error] 86#0: *1067234 [lua] balancer.lua:304: balancer_execute(): name resolution failed for ‘xxx.xxx.svc.cluster.local’: dns server error; 3 name error, client: 203.96.123.216, server: kong, request: “POST /oauth2/token/ HTTP/1.0”, host: “xxx.co.nz”
2017/05/14 22:47:41 [error] 88#0: *1067257 [lua] cluster.lua:20: log(): [cluster] could not retrieve nodes from datastore: [postgres error] [toip() name lookup failed]: dns server error; 3 name error, context: ngx.timer
2017/05/14 22:47:45 [error] 87#0: *1067281 [lua] postgres.lua:158: [postgres] could not cleanup TTLs: [toip() name lookup failed]: dns server error; 3 name error, context: ngx.timer
2017/05/14 22:47:51 [error] 85#0: *1067313 [lua] postgres.lua:158: [postgres] could not cleanup TTLs: [toip() name lookup failed]: dns server error; 3 name error, context: ngx.timer
2017/05/14 22:48:41 [error] 88#0: *1067529 [lua] cluster.lua:20: log(): [cluster] could not update node in datastore:[postgres error] [toip() name lookup failed]: dns server error; 3 name error, context: ngx.timer
2017/05/14 22:48:45 [error] 87#0: *1067553 [lua] postgres.lua:158: [postgres] could not cleanup TTLs: [toip() name lookup failed]: dns server error; 3 name error, context: ngx.timer
2017/05/14 22:48:51 [error] 85#0: *1067585 [lua] postgres.lua:158: [postgres] could not cleanup TTLs: [toip() name lookup failed]: dns server error; 3 name error, context: ngx.timer

Somehow similar to https://github.com/Mashape/kong/issues/2092 but not sure?

**Comment by pazjing** [comment]
We encounter this same issue on 0.10.2, very similar to the #2092. 
We hard code the KONG_PG_HOST to IP address, then the error stop and the admin API works. 
But we still have problem with the upstream urls resolution. 

We set the upstream_url=http://myservice.svc.cluster.local:1234. When try to send request, the error logs shows as below
2017/05/15 22:25:50 [error] 87#0: *482 [lua] balancer.lua:304: balancer_execute(): name resolution failed for 'myservice.svc.cluster.local': dns server error; 3 name error, client: 123.123.123.123, server: kong, request: "POST /oauth2/token/ HTTP/1.0", host: "my-api.company.com"

It works fine with 0.9.9 version.

**Comment by rcyrus** [comment]
I am seeing this issue as well with 0.10.2 

clients will attempt to generate an oauth token which will sometimes fail with: 
`{“message”:“An unexpected error occurred”}`

looking at the error log I can see corresponding messages:

    generate_token(): [postgres error] [toip() name lookup failed]: dns query returned no results, client: 10.125.116.7, server: kong, request: "POST /endpoint/oauth2/token HTTP/1.1", host: "gateway.myhost.com"`

Kong is running on Openshift 3.2 referencing a postgres database running in a different pod. 

`KONG_PG_HOST: kongdb-master.gateway.svc.cluster.local`

most requests are successful, I am seeing about 5% error. Kong is running a single node in a single openshift pod.

**Comment by Tieske** [comment]
I think these are all related to https://github.com/Mashape/lua-resty-dns-client/issues/14

@frederik79 @pazjing @rcyrus Can you please try to generate the extra logging info as mentioned in [this post](https://github.com/Mashape/lua-resty-dns-client/issues/14#issuecomment-301007869) ?

**Comment by Tieske** [comment]
another note: please use fully qualified domain names (the dns SEARCH and NDOTS directives have not been implemented yet, a change to do so is pending)

Please report back whether the problem persists.

**Comment by john-deng** [comment]
@frederik79 in case your did not solve this issue, you can check this out: https://github.com/john-deng/kong-openshift,

**Comment by frederik79** [comment]
@john-deng thanks. We have no problem running Kong 0.9.9 in Openshift. So the problem occured after the upgrade to 010.2.

@Tieske - We use full qualified domain names, but the problem still exists http://service.namespace.svc.cluster.local:8088/api/
Will collect the log files and post asap

**Comment by akashgangil** [comment]
I hit this too. Downgrading to 0.9.9.

**Comment by thibaultcha** [comment]
This should have been fixed in 0.10.3, see the related change notes.

**Comment by akashgangil** [comment]
I still see this on 0.10.3 container image I am using postgres as the db backend

`2017/05/30 18:19:21 [error] 82#0: *9 [lua] hooks.lua:120: member_update(): [postgres error] [toip() name lookup failed]: dns server error; 3 name error, client: 127.0.0.1, server: kong_admin, request: "POST /cluster/events/ HTTP/1.1", host: "127.0.0.1:8001"
2017/05/30 18:19:21 [notice] 82#0: signal 17 (SIGCHLD) received
2017/05/30 18:19:21 [notice] 83#0: signal 17 (SIGCHLD) received
2017/05/30 18:19:21 [notice] 84#0: signal 17 (SIGCHLD) received
2017/05/30 18:19:21 [notice] 87#0: signal 17 (SIGCHLD) received
2017/05/30 18:19:21 [notice] 88#0: signal 17 (SIGCHLD) received
2017/05/30 18:19:21 [notice] 85#0: signal 17 (SIGCHLD) received
2017/05/30 18:19:21 [notice] 89#0: signal 17 (SIGCHLD) received
2017/05/30 18:19:21 [notice] 86#0: signal 17 (SIGCHLD) received
2017/05/30 18:19:21 [error] 87#0: *22 [lua] hooks.lua:151: member_join(): [postgres error] [toip() name lookup failed]: dns server error; 3 name error, context: ngx.timer
2017/05/30 18:19:21 [error] 86#0: *23 [lua] hooks.lua:151: member_join(): [postgres error] [toip() name lookup failed]: dns server error; 3 name error, context: ngx.timer
2017/05/30 18:19:21 [error] 84#0: *24 [lua] events.lua:88: errlog(): worker-events: event callback failed; source=cluster, event=MEMBER-JOIN, pid=82 error='/usr/local/share/lua/5.1/pgmoon-mashape/init.lua:26: don't know how to calculate length of nil', data={"type":"MEMBER-JOIN","entity":"ip-172-27-1-188_0.0.0.0:7946_e0d19927415240d6a65aba37cff71f06\t172.27.1.188\t\t"}, context: ngx.timer
2017/05/30 18:19:21 [error] 88#0: *18 [lua] events.lua:88: errlog(): worker-events: event callback failed; source=cluster, event=MEMBER-JOIN, pid=82 error='/usr/local/share/lua/5.1/pgmoon-mashape/init.lua:26: don't know how to calculate length of nil', data={"type":"MEMBER-JOIN","entity":"ip-172-27-1-188_0.0.0.0:7946_e0d19927415240d6a65aba37cff71f06\t172.27.1.188\t\t"}, context: ngx.timer
2017/05/30 18:19:21 [error] 83#0: *21 [lua] hooks.lua:151: member_join(): [postgres error] [toip() name lookup failed]: dns server error; 3 name error, context: ngx.timer
2017/05/30 18:19:21 [error] 89#0: *20 [lua] hooks.lua:151: member_join(): [postgres error] [toip() name lookup failed]: dns server error; 3 name error, context: ngx.timer
2017/05/30 18:19:21 [notice] 85#0: signal 17 (SIGCHLD) received
2017/05/30 18:19:21 [notice] 85#0: signal 17 (SIGCHLD) received
2017/05/30 18:19:21 [notice] 85#0: signal 17 (SIGCHLD) received
2017/05/30 18:19:21 [error] 82#0: *72 [lua] responses.lua:107: handler(): [toip() name lookup failed]: dns server error; 3 name error, client: 127.0.0.1, server: kong_admin, request: "POST /cluster/events/ HTTP/1.1", host: "127.0.0.1:8001"
2017/05/30 18:19:22 [notice] 82#0: signal 17 (SIGCHLD) received
2017/05/30 18:19:23 [error] 83#0: *83 [lua] cluster.lua:20: log(): [cluster] [postgres error] connection refused, context: ngx.timer
2017/05/30 18:19:29 [error] 86#0: *151 [lua] cluster.lua:20: log(): [cluster] [postgres error] [toip() name lookup failed]: dns server error; 3 name error, context: ngx.timer
2017/05/30 18:19:41 [notice] 86#0: signal 17 (SIGCHLD) received
2017/05/30 18:19:50 [error] 84#0: *339 [lua] cluster.lua:20: log(): [cluster] could not update node in datastore:[postgres error] [toip() name lookup failed]: dns query returned no results, context: ngx.timer
2017/05/30 18:19:52 [notice] 82#0: signal 17 (SIGCHLD) received
2017/05/30 18:20:01 [error] 89#0: *446 [lua] responses.lua:107: handler(): [toip() name lookup failed]: dns server error; 3 name error, client: 192.168.7.15, server: kong_admin, request: "GET /apis HTTP/1.1", host: "master.akash-cluster.uhana.io:8001"
2017/05/30 18:20:04 [notice] 89#0: signal 17 (SIGCHLD) received
2017/05/30 18:20:11 [notice] 89#0: signal 17 (SIGCHLD) received
2017/05/30 18:20:20 [error] 87#0: *604 [lua] postgres.lua:158: [postgres] could not cleanup TTLs: connection refused, context: ngx.timer
2017/05/30 18:20:20 [error] 82#0: *608 [lua] postgres.lua:158: [postgres] could not cleanup TTLs: connection refused, context: ngx.timer
2017/05/30 18:20:20 [error] 85#0: *600 [lua] postgres.lua:158: [postgres] could not cleanup TTLs: connection refused, context: ngx.timer
2017/05/30 18:20:20 [error] 86#0: *624 [lua] postgres.lua:158: [postgres] could not cleanup TTLs: connection refused, context: ngx.timer
2017/05/30 18:20:20 [error] 89#0: *612 [lua] cluster.lua:20: log(): [cluster] could not update node in datastore:[postgres error] [toip() name lookup failed]: dns server error; 3 name error, context: ngx.timer
2017/05/30 18:20:22 [notice] 82#0: signal 17 (SIGCHLD) received
2017/05/30 18:20:41 [notice] 84#0: signal 17 (SIGCHLD) received
2017/05/30 18:20:50 [error] 89#0: *885 [lua] cluster.lua:20: log(): [cluster] could not update node in datastore:[postgres error] [toip() name lookup failed]: dns server error; 3 name error, context: ngx.timer
2017/05/30 18:20:52 [notice] 82#0: signal 17 (SIGCHLD) received
2017/05/30 18:20:54 [notice] 85#0: signal 17 (SIGCHLD) received
2017/05/30 18:20:54 [error] 85#0: *935 [lua] events.lua:88: errlog(): worker-events: event callback failed; source=cluster, event=ENTITY_CREATED, pid=85 error='/usr/local/share/lua/5.1/kong.lua:186: could not load APIs: [postgres error] [toip() name lookup failed]: dns server error; 3 name error', data={"type":"ENTITY_CREATED","primary_key":["id"],"collection":"apis","entity":{"id":"450bc7ce-148c-4e14-9b4e-6b3ab1748cc1"}}, client: 127.0.0.1, server: kong_admin, request: "POST /cluster/events/ HTTP/1.1", host: "127.0.0.1:8001"
2017/05/30 18:20:54 [error] 86#0: *947 [lua] events.lua:88: errlog(): worker-events: event callback failed; source=cluster, event=ENTITY_CREATED, pid=85 error='/usr/local/share/lua/5.1/kong.lua:186: could not load APIs: [postgres error] [toip() name lookup failed]: dns query returned no results', data={"type":"ENTITY_CREATED","primary_key":["id"],"collection":"apis","entity":{"id":"450bc7ce-148c-4e14-9b4e-6b3ab1748cc1"}}, context: ngx.timer
`

**Comment by Tieske** [comment]
@akashgangil thx for the logs, but I see no debug output. Can you run it as [instructed here](https://github.com/Mashape/kong/issues/2524#issuecomment-302413147)

**Comment by Tieske** [comment]
@frederik79 any update?

**Comment by akashgangil** [comment]
Hi @Tieske 

Attached are the logs. 

There are interleaved error messages in there. 
2017/06/08 17:31:25 [error] 93#0: *3076 [lua] postgres.lua:158: [postgres] could not cleanup TTLs: [toip() name lookup failed]: dns query returned no results, context: ngx.timer

[error.log.txt](https://github.com/Mashape/kong/files/1061868/error.log.txt)

**Comment by Tieske** [comment]
@akashgangil thanks for those. When reducing the log to only worker process "88", here's what I see:

Initial resolve, starts by trying a 33 (SRV) record
```
2017/06/08 17:25:26 [debug] 88#0: *20 [lua] client.lua:531: lookup(): [dns-client] querying 'kong-db.service.consul' for type 33 took 12.00008392334
2017/06/08 17:25:26 [debug] 88#0: *20 [lua] client.lua:574: lookup(): [dns-client] querying 'kong-db.service.consul' for type 33: entries 1 error nil nil
```
We get 1 entry returned, and no errors

Dereferencing that entry, start with a 33 (SRV) that fails, followed by a 1 (A) that succeeds:
```
2017/06/08 17:25:26 [debug] 88#0: *20 [lua] client.lua:531: lookup(): [dns-client] querying 'ip-172-27-1-188.node.dc1.consul' for type 33 took 0
2017/06/08 17:25:26 [debug] 88#0: *20 [lua] client.lua:574: lookup(): [dns-client] querying 'ip-172-27-1-188.node.dc1.consul' for type 33: entries 0 error 3 name error
2017/06/08 17:25:26 [debug] 88#0: *20 [lua] client.lua:531: lookup(): [dns-client] querying 'ip-172-27-1-188.node.dc1.consul' for type 1 took 0
2017/06/08 17:25:26 [debug] 88#0: *20 [lua] client.lua:574: lookup(): [dns-client] querying 'ip-172-27-1-188.node.dc1.consul' for type 1: entries 1 error nil nil
```
So now the initial resolve is complete.

Somewhat later the record expires and the next resolve is done, starting with 33 (SRV) again
```
2017/06/08 17:26:25 [debug] 88#0: *431 [lua] client.lua:531: lookup(): [dns-client] querying 'kong-db.service.consul' for type 33 took 0
2017/06/08 17:26:25 [debug] 88#0: *431 [lua] client.lua:574: lookup(): [dns-client] querying 'kong-db.service.consul' for type 33: entries 0 error 3 name error
```
Now this is inexplicable.... same query as before does not deliver any results...

Resolver continues checking the other types (A, AAAA, CNAME) but they all fail (obviously), and hence the final error regarding postgres being unable to cleanup the ttls
```
2017/06/08 17:26:25 [debug] 88#0: *431 [lua] client.lua:531: lookup(): [dns-client] querying 'kong-db.service.consul' for type 1 took 2.000093460083
2017/06/08 17:26:25 [debug] 88#0: *431 [lua] client.lua:574: lookup(): [dns-client] querying 'kong-db.service.consul' for type 1: entries 0 error 3 name error
2017/06/08 17:26:25 [debug] 88#0: *431 [lua] client.lua:531: lookup(): [dns-client] querying 'kong-db.service.consul' for type 28 took 0.99992752075195
2017/06/08 17:26:25 [debug] 88#0: *431 [lua] client.lua:574: lookup(): [dns-client] querying 'kong-db.service.consul' for type 28: entries 0 error 3 name error
2017/06/08 17:26:25 [debug] 88#0: *431 [lua] client.lua:531: lookup(): [dns-client] querying 'kong-db.service.consul' for type 5 took 0
2017/06/08 17:26:25 [debug] 88#0: *431 [lua] client.lua:574: lookup(): [dns-client] querying 'kong-db.service.consul' for type 5: entries 0 error 3 name error
2017/06/08 17:26:25 [error] 88#0: *431 [lua] postgres.lua:158: [postgres] could not cleanup TTLs: [toip() name lookup failed]: dns server error; 3 name error, context: ngx.timer
```

Again somewhat later, the previous error expires and a new try is done, starting with 33 (SRV) again
```
2017/06/08 17:27:25 [debug] 88#0: *958 [lua] client.lua:531: lookup(): [dns-client] querying 'kong-db.service.consul' for type 33 took 1.0001659393311
2017/06/08 17:27:25 [debug] 88#0: *958 [lua] client.lua:574: lookup(): [dns-client] querying 'kong-db.service.consul' for type 33: entries 1 error nil nil
```
Now that is nice, the initial 33 (SRV) record resolves again, so we have to go dereference it again.

The last successful lookup for this name was an A record, so that is being tried first:
```
2017/06/08 17:27:25 [debug] 88#0: *958 [lua] client.lua:531: lookup(): [dns-client] querying 'ip-172-27-1-188.node.dc1.consul' for type 1 took 8.9998245239258
2017/06/08 17:27:25 [debug] 88#0: *958 [lua] client.lua:574: lookup(): [dns-client] querying 'ip-172-27-1-188.node.dc1.consul' for type 1: entries 0 error 3 name error
```
Another inexplicable result... the A record is not found...

Falling through again, and all other queries fail, resulting in the same error again...
```
2017/06/08 17:27:25 [debug] 88#0: *958 [lua] client.lua:531: lookup(): [dns-client] querying 'ip-172-27-1-188.node.dc1.consul' for type 33 took 0
2017/06/08 17:27:25 [debug] 88#0: *958 [lua] client.lua:574: lookup(): [dns-client] querying 'ip-172-27-1-188.node.dc1.consul' for type 33: entries 0 error nil nil
2017/06/08 17:27:25 [debug] 88#0: *958 [lua] client.lua:531: lookup(): [dns-client] querying 'ip-172-27-1-188.node.dc1.consul' for type 28 took 1.0001659393311
2017/06/08 17:27:25 [debug] 88#0: *958 [lua] client.lua:574: lookup(): [dns-client] querying 'ip-172-27-1-188.node.dc1.consul' for type 28: entries 0 error 3 name error
2017/06/08 17:27:25 [debug] 88#0: *958 [lua] client.lua:531: lookup(): [dns-client] querying 'ip-172-27-1-188.node.dc1.consul' for type 5 took 0
2017/06/08 17:27:25 [debug] 88#0: *958 [lua] client.lua:574: lookup(): [dns-client] querying 'ip-172-27-1-188.node.dc1.consul' for type 5: entries 0 error nil nil
2017/06/08 17:27:25 [error] 88#0: *958 [lua] postgres.lua:158: [postgres] could not cleanup TTLs: [toip() name lookup failed]: dns query returned no results, context: ngx.timer
```

My first guess would be that is has multiple DNS servers configured which do not respond in the same way. Upon a query, it randomly picks a dns server to query from its list. Might be it mixes a configured DNS server with the defaults it loads from the `/etc/resolv.conf` file. Where the configured one would be consul, and the system dns would be unaware of the records we're looking for as they only live in consul.

I'll have to look further into that.

**Comment by Tieske** [comment]
@akashgangil could not find anything, so I updated the branch `0.4.x` to include a fix to not try ipv6 nameservers, and to log the configuration being used.

Would you mind giving that another try?

```
git clone https://github.com/Mashape/lua-resty-dns-client.git
git checkout 0.4.x
cd lua-resty-dns-client
luarocks make
```
then restart kong

```
export KONG_LOG_LEVEL=debug
kong restart
```
and check the error.log file

**Comment by Tieske** [comment]
fyi [this is the commit](https://github.com/Mashape/lua-resty-dns-client/commit/12cd7d583acb46d790d6e6b3ab11948a4538b731)

**Comment by maskerade** [comment]
Not sure if this is related / relevant but we have also just seen experienced a similar issue with DNS lookup failures after upgrading from 0.10.1 to 0.10.3 (running on CentOS 7 in AWS).

I enabled debug logging and could see the following:

```
2017/06/19 09:55:51 [debug] 9757#0: *10 [lua] cluster.lua:20: log(): [cluster] auto-joining
2017/06/19 09:55:51 [error] 9757#0: *10 [lua] cluster.lua:20: log(): [cluster] [postgres error] [toip() name lookup failed]: dns query returned no results, context: ngx.timer
2017/06/19 09:55:51 [debug] 9756#0: *14 [lua] client.lua:531: lookup(): [dns-client] querying 'kong-db.notrealdomain.com.' for type 33 took 1.0001659393311
2017/06/19 09:55:51 [debug] 9756#0: *14 [lua] client.lua:549: lookup(): [dns-client] removing: 5:kong-db.notrealdomain.com (name or type mismatch)
2017/06/19 09:55:51 [debug] 9756#0: *14 [lua] client.lua:574: lookup(): [dns-client] querying 'kong-db.notrealdomain.com.' for type 33: entries 0 error nil nil
2017/06/19 09:55:51 [debug] 9756#0: *14 [lua] client.lua:531: lookup(): [dns-client] querying 'kong-db.notrealdomain.com.' for type 1 took 0
2017/06/19 09:55:51 [debug] 9756#0: *14 [lua] client.lua:549: lookup(): [dns-client] removing: 5:kong-db.notrealdomain.com (name or type mismatch)
2017/06/19 09:55:51 [debug] 9756#0: *14 [lua] client.lua:574: lookup(): [dns-client] querying 'kong-db.notrealdomain.com.' for type 1: entries 0 error nil nil
2017/06/19 09:55:51 [debug] 9756#0: *14 [lua] client.lua:531: lookup(): [dns-client] querying 'kong-db.notrealdomain.com.' for type 28 took 0
2017/06/19 09:55:51 [debug] 9756#0: *14 [lua] client.lua:549: lookup(): [dns-client] removing: 5:kong-db.notrealdomain.com (name or type mismatch)
2017/06/19 09:55:51 [debug] 9756#0: *14 [lua] client.lua:574: lookup(): [dns-client] querying 'kong-db.notrealdomain.com.' for type 28: entries 0 error nil nil
2017/06/19 09:55:51 [debug] 9756#0: *14 [lua] client.lua:531: lookup(): [dns-client] querying 'kong-db.notrealdomain.com.' for type 5 took 0.99992752075195
2017/06/19 09:55:51 [debug] 9756#0: *14 [lua] client.lua:549: lookup(): [dns-client] removing: 5:kong-db.notrealdomain.com (name or type mismatch)
2017/06/19 09:55:51 [debug] 9756#0: *14 [lua] client.lua:574: lookup(): [dns-client] querying 'kong-db.notrealdomain.com.' for type 5: entries 0 error nil nil
2017/06/19 09:55:51 [error] 9756#0: *14 [lua] responses.lua:107: send_HTTP_INTERNAL_SERVER_ERROR(): [postgres error] [toip() name lookup failed]: dns query returned no results, client: 127.0.0.1, server: kong, request: "GET /apiendpoint/health HTTP/1.1", host: "api.notrealdomain.com"
2017/06/19 09:55:51 [info] 9756#0: *14 client 127.0.0.1 closed keepalive connection
```

Checking our configuration and the entry for `pg_host` had a trailing dot at the end of the DNS name, removing this and restarting Kong has resolved the issue

**Comment by iambate** [comment]
Hi @Tieske, I am seeing similar issue on kong 0.11.0rc1 and postgres 9.6

If the port returned by consul on a dns query for postgres server's hostname is different than the port of postgres, will this error occur?
Here are the details:
""
dig kong-db.service.consul. SRV

; <<>> DiG 9.9.5-3ubuntu0.8-Ubuntu <<>> kong-db.service.consul. SRV
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20569
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;kong-db.service.consul.		IN	SRV

;; ANSWER SECTION:
kong-db.service.consul.	0	IN	SRV	1 1 10001 ip-172-27-1-197.node.dc1.consul.

;; ADDITIONAL SECTION:
ip-172-27-1-197.node.dc1.consul. 0 IN	A	172.27.1.197

;; Query time: 0 msec
;; SERVER: 172.27.1.197#53(172.27.1.197)
;; WHEN: Tue Jul 18 03:40:18 UTC 2017
;; MSG SIZE  rcvd: 101
""

The postgres server is on port 5432(set as KONG_PG_PORT) but port returned by dig is 10001. Which port should be honored in this case
[error.log.zip](https://github.com/Mashape/kong/files/1154622/error.log.zip)
?

Attached is the error.log with debug enabled. Is this a bug or issue in configuration? Thanks

**Comment by Tieske** [comment]
@iambate the port returned by the dns server will override a manually specified port. So either properly configure consul to return port 5432, or use an A record instead of a SRV record.

In your case Kong will try to connect to port 10001.

**Comment by mvanholsteijn** [comment]
This problem occurs with a unqualified domain name (eg postgres) but also with a fqdn with a trailing dot. for instance postgres.local.

**Comment by Tieske** [comment]
A trailing dot is indeed not supported, but probably should.

Other than that, is there someone still seeing this issue?

The most common case we've seen is that the dns servers are not all responding with the same replies. Which causes intermittent failures, depending on which dns server is being hit.

Please report if you still see this, otherwise I'm inclined to close this.

**Comment by frederik79** [comment]
We tested this with 0.11. and the problem is gone. We are fine that this gets closed.

**Comment by thibaultcha** [comment]
@frederik79 Thanks for reporting back. Closing this. If a new problem arises, we should open a new issue for it, and not hijack this thread.

**Comment by lomori** [comment]
I'm seeing this problem. Kong 0.11.0 running under a Docker image (Ubuntu based) where Kong is build with support for unit tests (openresty busted).

Nslookup/dig/host work with a warning:

root@36468c25c16a:/kong-dev/kong# nslookup kong-database
Server:		192.168.65.1
Address:	192.168.65.1#53

** server can't find kong-database: NXDOMAIN
