### ISSUE TITLE
strip_request_path not being updated using PUT /apis 

### ISSUE THREAD

**Issue by PGBI** [Mashape/kong#765]
I have an API with strip_request_path being true:
```
{
  "upstream_url": "http://my-super-api.com",
  "id": "f289b20a-a0a4-4c88-ccfb-e1429e933400",
  "strip_request_path": true,
  "name": "test",
  "created_at": 1449109519000,
  "request_path": "/path"
}
```

When I'm making the following request to update strip_request_path to false:
> PUT /apis
```
{
  "upstream_url": "http://my-super-api.com",
  "id": "f289b20a-a0a4-4c88-ccfb-e1429e933400",
  "strip_request_path": false,
  "name": "test",
  "request_path": "/path"
}
```

I get the following response which seems ok:
```
{
  "upstream_url": "http://my-super-api.com",
  "id": "f289b20a-a0a4-4c88-ccfb-e1429e933400",
  "strip_request_path": false,
  "name": "test",
  "request_path": "/path"
}
```

However, when hitting `GET /apis/f289b20a-a0a4-4c88-ccfb-e1429e933400` again I still get a response with strip_request_path being true.

First I thought it was the same kind of problem as #720 but I tested with the `next` branch and still get the same problem.

**Comment by thibaultCha** [comment]
Hi,

Did you wait 60s or restarted Kong before hitting the proxy port after the change was made?

**Comment by PGBI** [comment]
nope, will try. Didn't think it was a caching problem because with a PATCH request I don't have this problem.

**Comment by thibaultCha** [comment]
Both method will have the same problem, but it is likely that you did not encountered it before by simply being lucky (the cache about to be refresh for example). #729 will get rid of this problem in the next major release.

**Comment by PGBI** [comment]
After 3 minutes and a few kong restart, strip_request_path is still true.

I also just tested again with PATCH, the change was correctly taken into account.

**Comment by thibaultCha** [comment]
Alright, so definitely a problem with the PUT method then.

**Comment by thibaultCha** [comment]
I believe this was fixed by the change to the plugins DAO in e8daea2cb43863048304ca0e3f91b39cbd4bc4fe, which is released in 0.5.4. The fix was not intended for this particular issue but for another use case, so I am not entirely sure. I will try it.

**Comment by PGBI** [comment]
I just tested with 0.5.4 and the problem remain. However, issue #720 seems to be solved although it is in the 0.6.0 milestone.
